// user
export const SET_NAME = "SET_NAME";
export const SET_TRACKING_LIST = "SET_TRACKING_LIST";
export const DELETE_TRACKING_LIST = "DELETE_TRACKING_LIST";
export const SET_TRACKING_LIST_NEW_LOGIN = "SET_TRACKING_LIST_NEW_LOGIN";

//event
export const SET_EVENT_TRACKING = "SET_EVENT_TRACKING";